name: Flutter Check

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
        working-directory: client-flutter
      - name: Analyze
        run: dart analyze
        working-directory: client-flutter
      - name: Test
        run: dart test
        working-directory: client-flutter
